### ISSUE TITLE
没有使用就报错了

### ISSUE THREAD

**Issue by 948489458** [deltazero-cz/node-p12-info#1]
![error](https://user-images.githubusercontent.com/58377707/189536032-11887e90-ea07-4164-8edd-a25458059fc9.jpg)
./node_modules/p12-info/dist/index.js 9:23
Module parse failed: Unexpected token (9:23)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     const p12 = forge.pkcs12.pkcs12FromAsn1(p12Asn1, false, pass);
|     const data = p12.getBags({ bagType: forge.pki.oids.certBag });
>     if (!data || !data?.[forge.pki.oids.certBag]?.[0])
|         throw new Error('Unable to parse certificate. Incorrect Password?');
|     // @ts-ignore

大佬,在vue2,下载,导入 import p12info from 'p12-info' ,就报上面的错误了,没有 走这步const parsed = p12info(certBuffer, certPassword),怎么解决呢

**Comment by deltazero-cz** [comment]
Hi, what is your node version? This package is compiled to JS es2020, older versions of node might not support it.

**Comment by 948489458** [comment]
> Hi, what is your node version? This package is compiled to JS es2020, older versions of node might not support it.

node versions is v14.18.3,Newer version

**Comment by deltazero-cz** [comment]
Hi, I've just tested the package against Node.js 14.20.0 LTS and it runs just fine.

Please check your Vue version supports Optional Chaining Operator `?.`
